// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE9RD7YNQ37wpJgXg-WBR7Q8S7gzFS37I',
    appId: '1:830686051254:web:fad559b1149d6ef4aa5f17',
    messagingSenderId: '830686051254',
    projectId: 'ispot-b18dc',
    authDomain: 'ispot-b18dc.firebaseapp.com',
    storageBucket: 'ispot-b18dc.firebasestorage.app',
    measurementId: 'G-DGKDD5RGB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxCddoDJJfAhY-TvVj248AW_Nzo9A3OJA',
    appId: '1:830686051254:android:aa12298f9204e8faaa5f17',
    messagingSenderId: '830686051254',
    projectId: 'ispot-b18dc',
    storageBucket: 'ispot-b18dc.firebasestorage.app',
  );
}
